export const GAME_LABELS = {
    player1: 'Player 1',
    player2: 'Player 2',
    gameOver: 'Game Over',
    draw: 'Draw',
    drawLabel: 'Draw', // For draw state text
    player1Starts: 'Player 1 starts.',
    turnSuffix: ' turn.',
    winsSuffix: ' wins.',
    drawSuffix: 'Draw.',
    discSettling: 'Disc settling.',
    readySuffix: ' ready.',
    localMatch: 'Local Match',
    matchStatus: 'Match Status',
    matchSettings: 'Match Settings',
    playerVsPlayer: 'Player vs Player',
    playerVsBot: 'Player vs Bot',
    botDifficulty: 'Bot Difficulty',
    botThinking: 'Bot thinking.',
    botPlaying: 'Bot is choosing a column.',
    botPlayer: 'Bot',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    turnHeader: 'Turn',
    modeHeader: 'Mode',
    difficultyHeader: 'Difficulty',
    movesHeader: 'Moves',
    hint: 'Hint',
    hintUnavailable: 'Hint unavailable.',
    restartMatch: 'Restart Match',
    resetMatch: 'Reset Match',
} as const;
